export const ticketsMockData = [
  {
    ticketId: 132,
    issue: "Transfers",
    priority: "Medium",
    status: "Awaiting",
    assigned: "Toyin",
    date: "18th Nov, 2025 14:19 PM",
  },
  {
    ticketId: 131,
    issue: "App Errors",
    priority: "Urgent",
    status: "Closed",
    assigned: "Ibukun",
    date: "18th Nov, 2025 14:19 PM",
  },
  {
    ticketId: 130,
    issue: "Login Issues",
    priority: "Urgent",
    status: "In progress",
    assigned: "Esther",
    date: "18th Nov, 2025 14:19 PM",
  },
  {
    ticketId: 129,
    issue: "Card Issues",
    priority: "High",
    status: "Awaiting",
    assigned: "David",
    date: "18th Nov, 2025 14:19 PM",
  },
  {
    ticketId: 128,
    issue: "Wallet Issues",
    priority: "Medium",
    status: "Closed",
    assigned: "Emmanuel",
    date: "18th Nov, 2025 14:19 PM",
  },
];

export const customersMockData = [
  {
    avatar: "https://i.pravatar.cc/150?img=12",
    email: "john.doe@example.com",
    customer: "John Doe",
    country: "Nigeria",
    status: "Active",
    kyc: "Verified",
    transactions: 124,
    dateJoined: "2024-01-15",
  },
  {
    avatar: "https://i.pravatar.cc/150?img=32",
    email: "amina.yusuf@example.com",
    customer: "Amina Yusuf",
    country: "Ghana",
    status: "Pending",
    kyc: "Pending",
    transactions: 12,
    dateJoined: "2024-03-02",
  },
  {
    avatar: "https://i.pravatar.cc/150?img=45",
    email: "samuel.okoye@example.com",
    customer: "Samuel Okoye",
    country: "Nigeria",
    status: "Active",
    kyc: "Verified",
    transactions: 89,
    dateJoined: "2023-11-21",
  },
  {
    avatar: "https://i.pravatar.cc/150?img=47",
    email: "fatima.bello@example.com",
    customer: "Fatima Bello",
    country: "Kenya",
    status: "Suspended",
    kyc: "Failed",
    transactions: 4,
    dateJoined: "2024-02-10",
  },
  {
    avatar: "https://i.pravatar.cc/150?img=59",
    email: "david.mensah@example.com",
    customer: "David Mensah",
    country: "Ghana",
    status: "Active",
    kyc: "Verified",
    transactions: 230,
    dateJoined: "2023-09-05",
  },
  {
    avatar: "https://i.pravatar.cc/150?img=68",
    email: "zainab.musa@example.com",
    customer: "Zainab Musa",
    country: "Nigeria",
    status: "Pending",
    kyc: "Pending",
    transactions: 0,
    dateJoined: "2024-04-01",
  },
];
